### ISSUE TITLE
No console output to apply fix

### ISSUE THREAD

**Issue by jmgilman** [markyjackson-taulia/pi-qemu-kernel#7]
Attempting the initial boot:

```
$QEMU -kernel $RPI_KERNEL \
-cpu arm1176 -m 256 \
-M versatilepb -no-reboot -serial stdio \
-append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash" \
-drive "file=$RPI_FS,index=0,media=disk,format=raw"
```

![2021-07-15_13-40-27](https://user-images.githubusercontent.com/2308444/125854725-04ee4490-6c20-4551-96e5-6744894424ed.gif)

The QEMU window opens with a black screen (assuming this is expected because of no video configuration). However, it appears `-serial stdio` should redirect output to the local Mac console but I'm not getting any output at all. I tried adding `console=ttyS0` to the kernel command to see if I could get it to capture anything additional but it didn't improve the situation.

I'll preface this with I'm new to QEMU and so this might be an operator error.

**Comment by jmgilman** [comment]
Found a similar thread with some good content in it. Particularly [this post](https://gist.github.com/hfreire/5846b7aa4ac9209699ba#gistcomment-3075521). The command seems to be almost identical but it's using newer versions. I was able to get the system fully booted and accessible over SSH using the versions documented there.

**Comment by markyjackson-taulia** [comment]
I will test this tonight and get a fix in

**Comment by markyjackson-taulia** [comment]
Also, thank you @jmgilman for this 😃
