### ISSUE TITLE
Update for new features in QEMU 7

### ISSUE THREAD

**Issue by vielmetti** [markyjackson-taulia/pi-qemu-kernel#9]
QEMU 7 has dropped, and it has some new Arm and Raspberry Pi support. Add those features to this install.

**Comment by markyjackson-taulia** [comment]
Rumor is a brew update will drop soon for https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qemu.rb

**Comment by vielmetti** [comment]
Rumor (actually fact) is that QEMU 7.0.0 for Mac is blocked due to a kernel bug in macOS 12.3, see the following:

https://github.com/Homebrew/homebrew-core/pull/99652
https://github.com/lima-vm/lima/issues/795
https://gitlab.com/qemu-project/qemu/-/issues/903#note_911000975

The last says "fixed in macOS 12.4 Beta 1" via @agraf .

**Comment by markyjackson-taulia** [comment]
Ok, I am going to leave this open until there is a resolution upstream

**Comment by vielmetti** [comment]
FYI there is now a macOS 12.4 Beta 2 available, with release notes at https://developer.apple.com/documentation/macos-release-notes/macos-12_4-release-notes - nothing specific yet regarding this issue.

I do not have a suitable hardware to beta test macOS releases on.

**Comment by markyjackson-taulia** [comment]
This has now been updated
